### ISSUE TITLE
Composer.json is missing a version number

### ISSUE THREAD

**Issue by wpillar** [graze/feed#1]
This is missing a version number: https://github.com/graze/feed/blob/master/composer.json

Since we've got two tags, `0.0.1` and `0.0.2`, we should have the latest tagged version of the version number in the composer.json.

**Comment by sjparkinson** [comment]
Nope, the version number can be derived from the git tags and is prefered.

https://getcomposer.org/doc/04-schema.md#version

**Comment by wpillar** [comment]
TIL.
